project:
  type: website
  output-dir: docs

website:
  title: "Kyrylo Koltunov"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Text_Analysis.qmd
        text: Text Analysis
      - href: Visuals.qmd
        text: Interactive Visuals

format:
  html:
    theme: sandstone
    css: styles.css





